from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class TaskStep(BaseModel):
    """Represents a single executable step in the generated plan."""
    tool: str = Field(..., description="The name of the tool or capability to use (e.g., 'web_search', 'llm').")
    reason: str = Field(..., description="The planner's reasoning for utilizing this tool.")
    parameters: Optional[Dict[str, Any]] = Field(
        default_factory=dict, 
        description="Dynamic parameters required for the tool execution."
    )

class ExecutionPlan(BaseModel):
    """The master plan generated by the Task Planner."""
    goal: str = Field(..., description="The synthesized main objective of the user prompt.")
    steps: List[TaskStep] = Field(..., description="The sequential order of operations to resolve the intent.")
    requires_tools: bool = Field(default=False, description="True if external tools/APIs are needed.")
    requires_research: bool = Field(default=False, description="True if web search, URLs, or RAG retrieval is required.")
    estimated_steps: int = Field(default=0, description="The total number of steps in the plan.")